-- DATE AND TIME FUNCTIONS
-- ORACLE'S 'DATE' DATA TYPE NOT ONLY HOLDS DATE IT ALSO HOLDS TIME

-- SYSDATE ==> RETURNS THE DATE BASED ON THE TIMEZONE OF SERVER OF DATABASE
-- CURRENT_DATE ==> RETURNS THE DATE BASED ON THE TIMEZONE SET TO PARTICULAR SESSION OF THE DATA BASE SESSION PARAMETERS

-- DATE(DATA TYPE) ==> DATE & TIME
-- TO_CHAR() ==> USED TO CONVERT A DATA INTO STRING, BASED ON A FORMAT MASK 


SELECT SYSDATE FROM dual;

SELECT CURRENT_DATE FROM dual;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM dual; -- > 'YEAR-MONTH-DAY'

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH12:MI:SS AM') FROM dual; -- > 'YEAR-MONTH-DAY HOURS(12 HOURS):MINUTES: SECONDS AM'


SELECT DBTIMEZONE FROM dual; -- GMT/UTC
SELECT SESSIONTIMEZONE  FROM dual;


SELECT TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD HH24:MI:SS')
FROM dual; -- Session time

-- SUBTRACT TWO DATES AND CAN GET HOW MANY DAYS ARE PRESENT IN BETWEEEN TWO DATES

SELECT
    TO_DATE('2025-08-02 13:35:07', 'YYYY-MM-DD HH24:MI:SS')
    -
    TO_DATE('2025-08-01 12:25:04', 'YYYY-MM-DD HH24:MI:SS')
FROM dual;

-- 1 DAY 1 HOURS 10 MINUTES 3 SECONDS
-- 3600 + 600 + 3 == > 4203 SECONDS

-- borrowal_date, return_date

-- TO_DATE() ==> USED TO CONVERT A STRING INTO A DATE BASED ON FORMAT MASK
-- TO_CHAR() ==> USED TO CONVERT A DATE INTO STRING BASED ON FORMAT MASK

SELECT TO_CHAR(CURRENT_DATE, 'YYYY-MON-DD') FROM dual; --> MONTH LIKE JAN,FEB,MAR,APR,....
SELECT TO_CHAR(CURRENT_DATE, 'YYYY-MONTH-DD') FROM dual; --> MONTH WITH FULL NAME
SELECT TO_CHAR(CURRENT_DATE, 'YYYY') FROM dual; --> ONLY YEAR
SELECT TO_CHAR(CURRENT_DATE, 'MM') FROM dual; -- > ONLY MONTH NUMBER
SELECT TO_CHAR(CURRENT_DATE, 'MON') FROM dual; --> ONLY MONTH LIKE JAN,FEB,MAR,...
SELECT TO_CHAR(CURRENT_DATE, 'MONTH') FROM dual; --> ONLY FULL NAME OF THE MONTH
SELECT TO_CHAR(CURRENT_DATE, 'DD') FROM dual;--> ONLY DAY
SELECT TO_CHAR(CURRENT_DATE, 'Day') FROM dual; --> ONLY NAME OF THE DAY
SELECT TO_CHAR(CURRENT_DATE, 'HH') FROM dual; --> HOURS
SELECT TO_CHAR(CURRENT_DATE, 'MI') FROM dual; --> MINUTES
SELECT TO_CHAR(CURRENT_DATE, 'SS') FROM dual; -->SECONDS


-- HOW MANY ORDERS WERE PLACE IN THE YEAR 2022 ?
-- WAY 1:
SELECT COUNT(*) AS order_count FROM
orders
WHERE
order_date >= TO_DATE('01-01-2022', 'DD-MM-YYYY')
and order_date <= TO_DATE('31-12-2022', 'DD-MM-YYYY');

-- WAY 2:
SELECT COUNT(*) AS order_count FROM
orders
WHERE TO_CHAR(order_date, 'YYYY') = 2022;

-- FIND OUT HOW MANY ORDERS ARE PLACE IN THE MONTH OF NOVEMBER ?
SELECT COUNT(*) AS order_count FROM
orders
WHERE TO_CHAR(order_date, 'MM') = 11;


-- COMING SOON WAIT

-- MONTHS_BETWEEN()
-- NEXT_DAY()
-- LAST_DAY()
-- ADD_MONTHS()
