-- TYPES OF JOOINS IN SQL
-- 1. INNNER JOIN
-- 2. OUTER JOIN (LEFT OUTER JOIN, RIGHT OUTER JOIN, FULL OUTER JOIN)
-- 3. SELF JOIN
-- 4. THETA JOIN
-- 5. CROSS JOIN
-- 6. NATURAL JOIN

-- 1. INNER JOIN
-- COMBINES ROW FROM TWO TABLES ONLY WHERE THE JOIN CONDITION
-- EVALUATED TO TRUE
-- SYNTAX :
SELECT col1,col2,...
FROM 
table1 t1
JOIN
table2 t2
ON t1.some_column = t2.some_column;

-- 2. OUTER JOIN
-- 2.1 LEFT OUTER JOIN
-- RETRIEVES ALL ROWS FROM THE LEFT TABLE AND MATCHING ROW FROM THE 
-- RIGHT TABLE. IF THERE IS NO MATCH, NULL IS RETURNED FOR THE RIGHT TABLE
-- SYNTAX :
SELECT col1,col2,...
FROM 
table1 t1
LEFT JOIN
table2 t2
ON t1.some_column = t2.some_column;

-- 2.2 RIGHT OUTER JOIN 
-- RETRIVES ALL ROWS FROM THE RIGHT TABLE AND MATCHING ROWS FROM THE LEFT TABLE.
-- IF THERE IS NO MATCH, NULL IS RETURNED FOR THE LEFT TABLE
-- SYNTAX :
SELECT col1,col2,...
FROM 
table1 t1
RIGHT JOIN
table2 t2
ON t1.some_column = t2.some_column;

-- 2.3 FULL OUTER JOIN
-- COMBINES TEH RESULTS OF BOTH LEFT AND RIGHT OUTER JOINS.
-- ALL ROWS FROM BOTH TABLES ARE ICLUDED,EVEN IF THEY DON'T MATCH.
-- SYNTAX :
SELECT col1,col2,...
FROM 
table1 t1
FULL JOIN
table2 t2
ON t1.some_column = t2.some_column;

-- 3. SELF JOIN
-- A TABLE IS JOINED WITH ITSELF.
SELECT col1,col2,...
FROM 
table1 t1
JOIN
table1 t2
ON t1.some_column = t2.some_column;

-- 4. THETA JOIN
-- A THETA JOIN IS A TYPE OF JOIN IN SQL WHERE THE CONDITION BETWEEN THE TOW TABLE USES A 
-- COMPARISION OPERATOR OTHE THAN EQUALITY(=)
-- IT CAN IVOLVE OTHER OPERATORS LIKE (<, <=, >, >=, ..)

-- 5. CROSS JOIN
-- 6. NATURAL JOIN




