-- VIEWS 
-- A VIEW IS A VIRTUAL TABLE BASED ON THE RESULT OF AN SQL QUERY
-- IT DOESN'T STORE DATA PHYSICALLY
-- IT DISPLAYS DATA STORED IN OTHER TABLES

-- TYPES OF VIEWS
-- 1. UPDATABLE VIEW
-- 2. NON-UPDATABLE VIEW
-- 3. MATERIALIZED VIEW

-- 1. UPDATABLE VIEW
-- AN UPDATABLE VIEW ALLOWS PERFORMING INSERT,UPDATE AND DELETE OPERATION ON THE BASE TABLE THROUGH THE VIEW.
-- THE VIEW MUST BE CREATED FROM A SINGLE TABLE 
-- NOT JOINS, GROUP BY FUNCIIONS ETC.. ARE INVOLVED

CREATE OR REPLACE VIEW emp_view AS
SELECT id, name, salary, department
FROM employee
WHERE department = 'SW';

SELECT * FROM emp_view;

UPDATE emp_view SET salary = salary + 1000 WHERE id = 101;
-- THIS UPDATE WILL CHANGE THE SALARY OF THE EMPLOYEE WITH ID 101 IF HE/SHE BELONGS TO SW DEPARTMENT

-- 2. NON-UPDATABLE VIEW
-- A NON-UPDATABLE VIEW IS A VIEW WHERE YOU CANNOT MODIFY DATA USING
-- INSERT ,UPDATE, DELETE
-- THIS HAPPEND WHEN A VIEW IS CREATED USING:
-- JOIN,GROUP BY, DISTINCT, AGGREGATE FUNCTIONS ETC,,.
CREATE or REPLACE VIEW dept_avg AS
SELECT department, AVG(salary) AS avg_salary
FROM employee
GROUP BY department;

SELECT * FROM dept_avg;

UPDATE dept_avg SET avg_salary = 90000 WHERE department = 'SW'; -- FAILS;

-- 3. MATERIALIZED VIEW 
-- A MATERIALIZED VIEW STORES THE ACTUAL DATA (NOT VIRTUAL)
-- IT IMPROVES PERFORMANCE FOR COMPLEX OR FREQUENTLY USED QUERIES 
-- BECAUSE THE RESUL IS PHYSICALLY SAVED AND CAN BE REFRESHED LATER

CREATE MATERIALIZED VIEW emp_summary AS
SELECT department, COUNT(*) AS total_emp, AVG(salary) AS avg_salary
FROM employee
GROUP BY department;

SELECT * FROM emp_summary;
-- MVIEW IS PERMENATLY STORED IN THE MEMORY
DELETE FROM employee WHERE id = 101; 
-- EVEN IF YOU DELETE THE RECORD MVIEW WILL FETCH THE LASTLY STORED DATA
-- IT WILL NOT GET AFFECTED

-- REFRESH THE MVIEW
EXEC DBMS_MVIEW.REFRESH('EMP_SUMMARY');

DROP VIEW emp_view;
DROP VIEW dept_avg;
DROP MATERIALIZED VIEW emp_summary;

