-- SUB-QUERIES
-- A SUB-QUERY IS QUERY INSIDE ANOTHER QUERY
-- IT IS USED TO RETRIEVE DATA THAT WILL BE USED BY THE MAIN (OUTER) QUERY
-- FOR COMPARISION OR FILTERING

-- TYPES OF SUB-QUERIES
-- 1. SINGLE ROW SUB-QUERY ==> RETURNS ONLY ONE ROW AND ONE COLUMN
-- 2. MULTIPLE ROW SUB-QUERY ==> RETURNS ONE OR MORE ROWS 
-- 3. CO-RELATED SUB-QUERY ==> THE INNER QUERY DEPENDS ON THE OUTER QUERY FOR ITS VALUE.
-- CO-RELATED SUB-QUERY RUNS ONCE FOR EVERY ROW OF THE OUTER QUERY



-- 1.  SINGLE ROW SUB-QUERY

-- EX: WRITE A QUERY TO DISPLAY THE NAME AND SALARY OF THE EMPLOYEES 
-- WHOSE SALARY IS GREATER THAN AVERGAGE SALARY OF ALL EMPLOYEES
SELECT e_name, salary 
FROM employee
WHERE salary > (SELECT AVG(salary) FROM employee);
-- HERE THE SUB QUERY RETURN ONLY ONE VALUE

-- EX: WRITE A QUERY TO DISPLAY THE EMP_ID,EMP_NAME,DEPT OF THE EMPLOYEE(S)
-- WHOSE SALARY IS EQUAL TO THE MAXIMUM SALARY OF THE EMPLOYEES
SELECT e_id,e_name,dept  
FROM employee
WHERE salary = (SELECT MAX(salary) FROM employee);
-- HERE ALSO THE SUB QUERY RETURN ONLY ONE VALUE


-- 2. MULTIPLE ROW SUBQUERY
-- IT WILL RETURN ONE OR MORE ROWS AND ONE OR MORE COLUMNS 

-- EX: WRITE A QUERY TO DISPALY THE EMP_ID,EMP_NAME OF THE EMPLOYEES 
-- WHOSE DOESN'T CONTAINS THE EMPLOYEES WITH LESS THAN FIFITY THOUSAND
SELECT e_id,e_name 
FROM employee
WHERE dept IN (SELECT DISTINCT dept FROM employee WHERE salary >= 50000);
-- HERE THE SUB QUERY RETURN ONE OR MORE ROWS AND ONE COLUMN AS RESULT

-- EX: WRITE A QUERY TO DISPLAY THE EMP_ID,EMP_NAME,DEPT OF THE EMPLOYEES
-- WHOSE SALARY IS MAXIMUM IN THEIR RESPECTIVE DEPARTMENT
SELECT e_id,e_name,dept
FROM employee
WHERE (dept,salary) IN (SELECT dept,MAX(salary) FROM employee GROUP BY dept);
-- HERE THE SUB QUERY RETURNS ALL DEPARTMENTS AND THEIR MAXIMUM SALARY
-- MORE THAN ONE ROW AND TWO COLUMNS


-- 3.CO-RELATED SUB-QUERY

-- EX: WRITE A QUERY TO DISPLAY THE EMP_ID,EMP_NAME,SALARY OF THE EMPLOYEES
-- WHOSE SALARY IS GREATER THAN AVERAGE SALARY OF EMPLOYESS BELONGS TO THEIR DEPARTMENT(USING CO-RELATED SUB-QUERY)
SELECT e_id, e_name, salary
FROM employee e
WHERE salary > (SELECT AVG(salary) FROM employee WHERE dept = e.dept);
-- HERE THE INNER QUERY RUNS ONE TIME FOR EACH ROW OF THE OUTER QUERY
-- IT MEANS FOR EVERY EMPLOYEE IT WILL CALUCULATES THE AVG SALARY OF THE EMPLOYEES
-- IN THEIR DEPARMENT 

-- EX: WRITE A QUERY TO DISPLAY THE EMP_ID,EMP_NAME,SALARY OF THE EMPLOYEES
-- WHOSE SALARY IS EQUAL TO MAXIMUM SALARY OF EMPLOYEES BELONGS TO THEIR DEPARTMENT(USING CO-RELATED SUB-QUERY)
SELECT e_id, e_name, salary
FROM employee e
WHERE salary = (SELECT MAX(salary) FROM employee WHERE dept = e.dept);
