-- DISTINCT: 
-- IS USED TO GET DISTINCT VALUES FROM SINGLE OR MULTIPLE COLUMN(S)

SELECT DISTINCT department FROM employee;
--  GETS ALL DEPARTMENTS WHICH ARE DIFFERENT

SELECT DISTINCT department , age FROM employee;
 -- GETS ALL THE DISTINCT PAIRS

SELECT DISTINCT departemnt,age,gender FROM employee;
--  GETS ALL THE DISITINCT TRIPLETS

-- IN/NOT IN:
-- USED TO CHECK WHEATHER A VALUE IS PART OF COLLECTION OF VALUES IN COMPARISON
-- IT OFTEN SERVES AS ALTERNATIVE FOR LOGICAL ORs

SELECT * FROM employee WHERE department IN ('SW', 'HR');-- INCLUSION

SELECT * FROM employee WHERE department NOT IN ('SW', 'HR');-- EXCULSION

-- ORDER BY:
-- ORDER BY USED TO ORDER THE DATA IN EITHER ASCENDING OR DESCENDING BASED ON 1 OR MULTIPLE COLUMNS
-- BY DEFAULT ORDER BY ORDERS THE DATA IN ASCENDING ORDER 
-- DESCENDING ORDER REQUIRES AN EXPLICIT MENTION OF 'DESC' KEYWORD
-- WHILE ARRANGING IN ASC ORDER NULLs COME LAST
-- WHILE ARRANGING IN DESC ORDER NULLs COME FIRST

SELECT * FROM employee ORDER BY age;
-- ORDERS THE DATA IN ASCENDING ORDER BASED ON THE AGE OF  EMPLOYEES

SELECT * FROM employee ORDER BY date_of_joining;
-- ORDERS THE DATA IN ASCENDING ORDER BASED ON THE DATE OF JOINING OF EMPLOYEE

SELECT * FROM employee ORDER BY department;
-- ORDERS THE DATA IN ALPHABETICALLY ASCENDING ORDER BASED ON THE DEPARTMENT OF EMPLOYEE

SELECT * FROM employee ORDER BY department DESC;
-- ORDERS THE DATA IN ALPHABETICALLY DESCENDING ORDER BASED ON THE DEPARTMENT OF EMPLOYEE

SELECT * FROM employee ORDER BY salary DESC NULLS LAST;-- NULLS COMES LAST
-- ORDERS THE DATA IN ALPHABETICALLY DESCENDING ORDER BASED ON THE DEPARTMENT OF EMPLOYEE

-- ORDER BY -> USING MULTIPLE COULUMS WE CAN BREAK THE TIES

SELECT id, name, salary, age, department FROM employee ORDER BY salary DESC, age, department DESC;
-- FIRST IT ARRANGES THE DATA BASED ON SALARY IN DESCENDING ORDER
-- THEN IF ANY TIES IN SALARY IT ARRANGES ALL TIED SALARIES IN ASCENDING ORDER BASED ON AGE
-- AGAIN IF THERE IS ANY TIES IN AGES IT ARRANGES ALL TIED AGES IN DESCENDING ORDER BASED ON DEPARTMENT
-- PROCESS CONTINUS IF WE ADD ANY EXTRA COLUMN

