-- AGGREGATE FUNCTIONS: 
-- USED TO FIND THE MAX(), MIN(), AVG(), SUM(), COUNT() OF COLUMN DATA

-- SUM() ->  WORKS ON ONLY NUMBERIC COLUMNS ONLY
SELECT SUM(salary) FROM employee WHERE department = 'HR';
-- GETS THE SUM OF SALRIES OF EMPLOYEES WHOSE DEPARTMENT IS 'HR'

SELECT SUM(age) FROM employee;
-- GETS THE SUM OF AGES OF EMPLOYEES

SELECT SUM(salary) FROM employee WHERE gender = 'Female';
-- GETS THE SUM OF SALARIES OF FEMALE EMPLOYEES

SELECT SUM(age), SUM(salary) FROM employee;
-- GETS THE SUM OF AGES AND SALARY OF EMPLOYEES

-- COUNT() -> COUNT IS USED TO GIVE HOW MANY

-- FIND OUT HOW MANY EMPLOYEE ARE WORKING UNDER HR DEPARTMENT
SELECT COUNT(department) FROM employee WHERE department = 'HR';

-- USING COUNT WITH COULUMN NAME DOESN'T COUNT NULL
SELECT COUNT(department) FROM employee;

-- COUNT(*) -- USED TO COUNT ENTIRE ROWS 
SELECT COUNT(*) FROM employee;

-- FIND OUT HOW MANY FEMALE EMPLOYESS ARE WORKING IN OPERATIONS DEPARTMENT
SELECT COUNT(*) FROM employee WHERE department = 'Operations' AND gender = 'Female';

SELECT COUNT(gender), COUNT(age) FROM employee;
-- GETS THE COUNT OF GENDER AND AGES FROM EMPLOYEE DOESN'T COUNT THE NULLs


-- AVG(),MIN(),MAX()
-- AVG() -> WORKS ONLY ON NUMBERIC COLUMN(S)
--> MIN(),MAX() -> WORKS FOR BOTH ALPHABET AND NUMERIC COLUMN(S)

SELECT AVG(salary), MIN(salary), MAX(salary)FROM employee;
-- GETS AVERAGE,MINIMUM SALARY,MAXIMUM SALARY OF EMPLOYEES

SELECT AVG(salary), MIN(salary), MAX(salary) FROM employee WHERE department = 'HR';
-- GETS AVERAGE,MINIMUM SALARY,MAXIMUM SALARY OF EMPLOYEES WHOSE DEPARTMENT IS 'HR'



SELECT MAX(salary) - MIN(salary) AS sal_diff FROM employee;
-- GETS THE DIFFERENCE OF MAX AND MIN SLARIES OF THE EMPLOYEE

-- FINDING MAXIMUM NAME(BASED ON ALPHABET ORDER) FROM 'HR' DEPARTMENT
SELECT MAX(name) FROM employee WHERE department = 'HR';


SELECT MAX(date_of_joining) AS max_doj FROM employee;
-- GETS THE MAXIMUM DATE OF JOINING OF AN EMPLOYEE
