-- GROUP BY, HAVING:

-- GROUP BY
-- USED TO GROUP THE DATA BASED ON EITHER ONE COLUMN OR MULTIPLE COLUMNS
-- MOSTLY GROUP BY IS USED WITH AGGREGATE FUNCTIONS 
-- ALL THE COLUMNS USED IN SELECT STATEMENT OF A GROUP BY QUERY MUST ALSO
-- BE USED IN GROUP BY CLAUSE OR MUST BE AGGREGATED

-- FIND HOW MANY EMPLOYEES ARE WORKING IN EACH DEPARTMENT
SELECT department, COUNT(*) AS emp_count FROM employee GROUP BY department;

-- FIND,HOW MANY FEMALE,MALE EMPLOYEES ARE WORKING IN THE ORGANISATION
SELECT gender, COUNT(*) as emp_count FROM employee GROUP BY gender;

-- FIND MAXIMUM,MINIMUM,SUM OF SLARIES FROM EMPLOYEES TABLE FOR EACH DEPARTMENT
SELECT department, MAX(salary), MIN(salary), SUM(salary) FROM employee GROUP BY department;

-- WHERE + GROUP BY

-- FIND HOW MANY EMPLOYEES ARE THERE FROM EACH DEPARTMENT THAT ARE EARNING MORE THAN 60K 
-- SELECT --- FROM ---- WHERE ---- GROUP BY
SELECT department, COUNT(*) AS emp_cnt
FROM employee
WHERE salary > 60000
GROUP BY department;

-- AND ORDER THEN BY EMP_COUNT
-- SELECT -> FROM -> WHERE -> GROUP BY -> ORDER BY
SELECT department, COUNT(*) AS emp_cnt
FROM employee
WHERE salary > 60000
GROUP BY department
ORDER BY emp_cnt;


-- GROUP BY -> ON MULTIPLE COLUMNS

-- FIND MAXIMUM,MINIMUM,SUM OF SLARIES FROM EMPLOYEES TABLE FOR EACH DEPARTMENT SEPARTE BY GENDERS TOO
SELECT department, gender, COUNT(*)
FROM employee
GROUP BY department, gender;


-- HAVING :
-- HAVING IS USED TO FILTER THE DATA AFTER GROUPING 
-- WHERE IS USED TO FILTER THE DATA BEFORE GROUPING is used to filter the rows
-- SELECT -> FROM -> WHERE -> GROUP BY -> HAVING -> ORDER BY

SELECT department, COUNT(*) AS emp_cnt
FROM employee
GROUP BY department
HAVING emp_cnt > 27;
